### ISSUE TITLE
error: Chrome died immediately after restart

### ISSUE THREAD

**Issue by ball6847** [icilalune/prerender#2]
I tested your docker image and found that it's not working, got these errors

```
$ docker run --name prerender --rm -it -p 3000:3000 lune/prerender:chrome-headless

> prerender@5.2.0 start /usr/src/app
> node server.js

2018-01-24T20:33:27.750Z Starting Prerender
2018-01-24T20:33:27.752Z Starting Chrome
2018-01-24T20:33:27.760Z Prerender server accepting requests on port 3000
2018-01-24T20:33:27.810Z Chrome connection closed... restarting Chrome
2018-01-24T20:33:27.811Z Chrome died immediately after restart... stopping Prerender
```

after googled and tested, it looks like we have 2 options to make chrome headless spawned successfully

1. use `--no-sandbox` flags for `chrome-browser`
2. use `--cap-add=SYS_ADMIN` for docker 

With `--cap-add=SYS_ADMIN` chrome-browser spawned without any error.
With `--no-sandbox` chrome-browser spawned with warning `libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted` but process still alive after spawned and functioning properly.

------------------------

To add `--no-sandbox` to prerender with need to modify server.js add specify our own chromeFlags

```js
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
  chromeFlags: [
    '--headless',
    '--disable-gpu',
    '--remote-debugging-port=9222',
    '--hide-scrollbars',
    '--no-sandbox'
  ]
});

server.use(prerender.sendPrerenderHeader());
// server.use(prerender.blockResources());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();
```

I have no idea which one is a good way to go in term of security, but hope this help.

Good work, anyway.

Thanks

**Comment by morvans** [comment]
Hi @ball6847,
As you found out, Chrome needs some capabilities which docker forbids by default.
This has been discussed (with solutions) in https://github.com/icilalune/prerender/pull/1#issuecomment-358009317
Basically, `--cap-add=SYS_ADMIN` is the simpler way to go but maybe a bit _too much_. Read the PR comment to find a more fine grained solution.
